---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["private_network", {ip: "192.168.33.33"}]
  
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: foreman
    run_list:
      - recipe[kitchen-foreman::default]
    attributes:
