name             'kitchen-foreman'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kitchen-foreman'
long_description 'Installs/Configures kitchen-foreman'
version          '0.1.0'
